# Generated by Django 4.2 on 2023-05-31 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('brand', models.CharField(choices=[('Skechers', 'Skechers'), ('Adidas', 'Adidas'), ('ASICS', 'Asics'), ('Gucci', 'Gucci'), ('Nike', 'Nike'), ('Puma', 'Puma'), ('Vans', 'Vans')], max_length=10)),
                ('type', models.CharField(choices=[('running', 'Running'), ('hiking', 'Hiking'), ('soccer', 'Soccer'), ('sport', 'Sport'), ('boot', 'Boot')], max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Both')], max_length=6)),
                ('images', models.JSONField(blank=True, default={})),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
